name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: denoland/setup-deno@main
      with:
        deno-version: ~1.12
    - run: npm ci --ignore-scripts
    - run: npm run --silent prepare
    - run: npm run --silent test

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@main
      with:
        deno-version: ~1.12
    - run: npm run --silent fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@main
      with:
        deno-version: ~1.11
    - run: npm run --silent lint
