name: CI

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@main
      with:
        deno-version: 1.9.2
    - run: npm ci --ignore-scripts
    - run: npm run --silent prepare

  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@main
      with:
        deno-version: 1.9.2
    - run: npm run --silent fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: denoland/setup-deno@main
      with:
        deno-version: 1.9.2
    - run: npm run --silent lint
